### ISSUE TITLE
Unusable

### ISSUE THREAD

**Issue by Per0x** [ravernkoh/transrt#1]
This is a very good idea, but unfortunately it's not workable in practice because I always get a 429 error because of the DeepL limit.
It only works for small texts to be translated, but you don't need a translator for a small .srt

**Comment by ravern** [comment]
(Apologies for the late reply, was overseas)

Yeah, I also kept getting the 429 error when I was building this. Unfortunately I do not have access to the actual DeepL API, so I am unable to use that or build for it.

I will however add a note in the README about the 429 error.
